name: fx_dart
description: Provide Debuggable Functional Program
version: 0.0.1
homepage: https://github.com/bansooknam/fxDart

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:

  freezed_annotation: ^2.4.1
  fxdart:
    path: ..


dev_dependencies:

