name: fxdart
description: Provide Debuggable Functional Program
version: 0.0.1
homepage: https://github.com/bansooknam/fxDart

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:

dev_dependencies:
  test: ^1.24.4