import 'package:test/test.dart';

import '../../tool/playground_source.dart';

void main() {
  test('ddcVersionOf reads the compileNewDDC header', () {
    const js = '// Generated by DDC, the Dart Development Compiler '
        '(to JavaScript).\n'
        '// Version: 3.12.2 (stable) (Tue Jun 9 01:11:39 2026 -0700) '
        'on "linux_x64"\n'
        '// Module: main.dart\n';
    expect(ddcVersionOf(js), '3.12.2');
  });

  test('ddcVersionOf returns null when the header is missing', () {
    expect(ddcVersionOf('dartDevEmbedder.defineLibrary("x", {});'), isNull);
  });

  test('a 3.12.2 prebuilt does not match a 3.13.1 runtime', () {
    const js = '// Version: 3.12.2 (stable)\n';
    expect(ddcVersionOf(js), isNot('3.13.1'));
  });
}
