#!/usr/bin/env bash
# Generates docs/assets/fxdart_single.dart: a single-file build of fxdart for
# use in a web playground (the file is meant to be prepended to user code and
# compiled by the DartPad compile service).
#
# Rerunnable: this script always regenerates the output from scratch.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_DIR="$ROOT/docs/assets"
OUT="$OUT_DIR/fxdart_single.dart"

mkdir -p "$OUT_DIR"

# Files to concatenate, in order. fx.dart is handled separately below because
# it needs a source transform.
FILES=(
  "lib/src/async_iterable.dart"
  "lib/src/pipe.dart"
  "lib/src/lazy/map.dart"
  "lib/src/lazy/filter.dart"
  "lib/src/lazy/take_drop.dart"
  "lib/src/lazy/zip.dart"
  "lib/src/lazy/combine.dart"
  "lib/src/strict/aggregate.dart"
  "lib/src/strict/access.dart"
  "lib/src/strict/object.dart"
  "lib/src/strict/func.dart"
  "lib/src/strict/curried.dart"
  "lib/src/strict/predicates.dart"
  "lib/src/dart_aliases.dart"
  "lib/src/util/timing.dart"
  "lib/src/util/shuffle.dart"
)

# Strips lines that start with `import `, `export `, or the exact `library;`
# directive.
strip_directives() {
  grep -vE '^(import |export )' "$1" | grep -vE '^library;$'
}

{
  cat <<'HEADER'
// GENERATED by tools/build_single_file.sh — single-file build of fxdart for the web playground. Do not edit.
// ignore_for_file: deprecated_member_use_from_same_package, unused_element
import 'dart:async';
import 'dart:math' as math;
HEADER

  for f in "${FILES[@]}"; do
    echo ""
    echo "// ---- $f ----"
    strip_directives "$ROOT/$f"
  done

  # fx.dart is special: it calls top-level functions through import prefixes
  # (l., s., async_.) because its instance methods shadow the top-level names
  # (e.g. inside class Fx, `map` refers to the instance method). Those
  # prefixes don't exist once everything is merged into one file, so rewrite
  # every prefixed reference to a `_$NAME` wrapper defined further below.
  echo ""
  echo "// ---- lib/src/fx.dart (transformed: l./s./async_. -> _\$NAME) ----"
  strip_directives "$ROOT/lib/src/fx.dart" | perl -pe '
    s/(?<![A-Za-z0-9_])l\.([a-zA-Z0-9_]+)/_\$$1/g;
    s/(?<![A-Za-z0-9_])s\.([a-zA-Z0-9_]+)/_\$$1/g;
    s/(?<![A-Za-z0-9_])async_\.([a-zA-Z0-9_]+)/_\$$1/g;
  '

  # Wrapper section: every `_$NAME` used above, defined as a small top-level
  # delegating function. At top level the plain names resolve to the
  # top-level functions from the concatenated files (not to Fx/FxAsync
  # instance methods, which only shadow them inside the class body), so these
  # wrappers are legal and just forward the call.
  #
  # This list is static. It was generated once by hand from:
  #   grep -oE '(l|s|async_)\.[a-zA-Z0-9_]+' lib/src/fx.dart | sort -u
  # (ignoring the false matches `s.dart` / `s._inner` that come from import
  # lines / `this._inner`), cross-checked against each function's signature
  # in the lib/src source files.
  cat <<'WRAPPERS'

// ---- wrappers for fx.dart's l./s./async_. prefixed calls ----

// async_iterable.dart
FxAsyncIterable<T> _$toAsync<T>(Iterable<FutureOr<T>> iterable) =>
    toAsync(iterable);

// lazy/map.dart
Iterable<B> _$map<A, B>(B Function(A a) f, Iterable<A> iterable) =>
    map(f, iterable);
FxAsyncIterable<B> _$mapAsync<A, B>(
        FutureOr<B> Function(A a) f, FxAsyncIterable<A> iterable) =>
    mapAsync(f, iterable);
Iterable<A> _$peek<A>(void Function(A a) f, Iterable<A> iterable) =>
    peek(f, iterable);
FxAsyncIterable<A> _$peekAsync<A>(
        FutureOr<void> Function(A a) f, FxAsyncIterable<A> iterable) =>
    peekAsync(f, iterable);
Iterable<dynamic> _$flat(Iterable<dynamic> iterable, [int depth = 1]) =>
    flat(iterable, depth);
FxAsyncIterable<dynamic> _$flatAsync(FxAsyncIterable<dynamic> iterable,
        [int depth = 1]) =>
    flatAsync(iterable, depth);
Iterable<B> _$flatMap<A, B>(Iterable<B> Function(A a) f, Iterable<A> iterable) =>
    flatMap(f, iterable);
FxAsyncIterable<B> _$flatMapAsync<A, B>(
        FutureOr<Iterable<B>> Function(A a) f, FxAsyncIterable<A> iterable) =>
    flatMapAsync(f, iterable);
Iterable<B> _$scan<A, B>(
        B Function(B acc, A a) f, B seed, Iterable<A> iterable) =>
    scan(f, seed, iterable);
FxAsyncIterable<B> _$scanAsync<A, B>(FutureOr<B> Function(B acc, A a) f,
        FutureOr<B> seed, FxAsyncIterable<A> iterable) =>
    scanAsync(f, seed, iterable);

// lazy/filter.dart
Iterable<A> _$filter<A>(bool Function(A a) f, Iterable<A> iterable) =>
    filter(f, iterable);
FxAsyncIterable<A> _$filterAsync<A>(
        FutureOr<bool> Function(A a) f, FxAsyncIterable<A> iterable) =>
    filterAsync(f, iterable);
Iterable<A> _$reject<A>(bool Function(A a) f, Iterable<A> iterable) =>
    reject(f, iterable);
FxAsyncIterable<A> _$rejectAsync<A>(
        FutureOr<bool> Function(A a) f, FxAsyncIterable<A> iterable) =>
    rejectAsync(f, iterable);
Iterable<A> _$uniq<A>(Iterable<A> iterable) => uniq(iterable);
FxAsyncIterable<A> _$uniqAsync<A>(FxAsyncIterable<A> iterable) =>
    uniqAsync(iterable);
Iterable<A> _$uniqBy<A, B>(B Function(A a) f, Iterable<A> iterable) =>
    uniqBy(f, iterable);
FxAsyncIterable<A> _$uniqByAsync<A, B>(
        FutureOr<B> Function(A a) f, FxAsyncIterable<A> iterable) =>
    uniqByAsync(f, iterable);

// lazy/take_drop.dart
Iterable<A> _$take<A>(int length, Iterable<A> iterable) =>
    take(length, iterable);
FxAsyncIterable<A> _$takeAsync<A>(int length, FxAsyncIterable<A> iterable) =>
    takeAsync(length, iterable);
Iterable<A> _$takeRight<A>(int length, Iterable<A> iterable) =>
    takeRight(length, iterable);
FxAsyncIterable<A> _$takeRightAsync<A>(
        int length, FxAsyncIterable<A> iterable) =>
    takeRightAsync(length, iterable);
Iterable<A> _$takeWhile<A>(bool Function(A a) f, Iterable<A> iterable) =>
    takeWhile(f, iterable);
FxAsyncIterable<A> _$takeWhileAsync<A>(
        FutureOr<bool> Function(A a) f, FxAsyncIterable<A> iterable) =>
    takeWhileAsync(f, iterable);
Iterable<A> _$takeUntilInclusive<A>(
        bool Function(A a) f, Iterable<A> iterable) =>
    takeUntilInclusive(f, iterable);
FxAsyncIterable<A> _$takeUntilInclusiveAsync<A>(
        FutureOr<bool> Function(A a) f, FxAsyncIterable<A> iterable) =>
    takeUntilInclusiveAsync(f, iterable);
Iterable<A> _$drop<A>(int length, Iterable<A> iterable) =>
    drop(length, iterable);
FxAsyncIterable<A> _$dropAsync<A>(int length, FxAsyncIterable<A> iterable) =>
    dropAsync(length, iterable);
Iterable<A> _$dropRight<A>(int length, Iterable<A> iterable) =>
    dropRight(length, iterable);
FxAsyncIterable<A> _$dropRightAsync<A>(
        int length, FxAsyncIterable<A> iterable) =>
    dropRightAsync(length, iterable);
Iterable<A> _$dropWhile<A>(bool Function(A a) f, Iterable<A> iterable) =>
    dropWhile(f, iterable);
FxAsyncIterable<A> _$dropWhileAsync<A>(
        FutureOr<bool> Function(A a) f, FxAsyncIterable<A> iterable) =>
    dropWhileAsync(f, iterable);
Iterable<A> _$dropUntil<A>(bool Function(A a) f, Iterable<A> iterable) =>
    dropUntil(f, iterable);
FxAsyncIterable<A> _$dropUntilAsync<A>(
        FutureOr<bool> Function(A a) f, FxAsyncIterable<A> iterable) =>
    dropUntilAsync(f, iterable);
Iterable<A> _$slice<A>(int start, Iterable<A> iterable, [int? end]) =>
    slice(start, iterable, end);
FxAsyncIterable<A> _$sliceAsync<A>(int start, FxAsyncIterable<A> iterable,
        [int? end]) =>
    sliceAsync(start, iterable, end);
Iterable<List<A>> _$chunk<A>(int size, Iterable<A> iterable) =>
    chunk(size, iterable);
FxAsyncIterable<List<A>> _$chunkAsync<A>(
        int size, FxAsyncIterable<A> iterable) =>
    chunkAsync(size, iterable);

// lazy/zip.dart
Iterable<(A, B)> _$zip<A, B>(Iterable<A> iterable1, Iterable<B> iterable2) =>
    zip(iterable1, iterable2);
FxAsyncIterable<(A, B)> _$zipAsync<A, B>(
        FxAsyncIterable<A> iterable1, FxAsyncIterable<B> iterable2) =>
    zipAsync(iterable1, iterable2);
Iterable<(int, A)> _$zipWithIndex<A>(Iterable<A> iterable) =>
    zipWithIndex(iterable);
FxAsyncIterable<(int, A)> _$zipWithIndexAsync<A>(
        FxAsyncIterable<A> iterable) =>
    zipWithIndexAsync(iterable);

// lazy/combine.dart
Iterable<A> _$append<A>(A a, Iterable<A> iterable) => append(a, iterable);
FxAsyncIterable<A> _$appendAsync<A>(
        FutureOr<A> a, FxAsyncIterable<A> iterable) =>
    appendAsync(a, iterable);
Iterable<A> _$prepend<A>(A a, Iterable<A> iterable) => prepend(a, iterable);
FxAsyncIterable<A> _$prependAsync<A>(
        FutureOr<A> a, FxAsyncIterable<A> iterable) =>
    prependAsync(a, iterable);
Iterable<A> _$concat<A>(Iterable<A> iterable1, Iterable<A> iterable2) =>
    concat(iterable1, iterable2);
FxAsyncIterable<A> _$concatAsync<A>(
        FxAsyncIterable<A> iterable1, FxAsyncIterable<A> iterable2) =>
    concatAsync(iterable1, iterable2);
Iterable<A> _$reverse<A>(Iterable<A> iterable) => reverse(iterable);
FxAsyncIterable<A> _$reverseAsync<A>(FxAsyncIterable<A> iterable) =>
    reverseAsync(iterable);
Iterable<T> _$cycle<T>(Iterable<T> iterable) => cycle(iterable);
FxAsyncIterable<T> _$cycleAsync<T>(FxAsyncIterable<T> iterable) =>
    cycleAsync(iterable);

// strict/aggregate.dart
List<A> _$toList<A>(Iterable<A> iterable) => toList(iterable);
Future<List<A>> _$toListAsync<A>(FxAsyncIterable<A> iterable) =>
    toListAsync(iterable);
void _$each<A>(void Function(A a) f, Iterable<A> iterable) => each(f, iterable);
Future<void> _$eachAsync<A>(
        FutureOr<void> Function(A a) f, FxAsyncIterable<A> iterable) =>
    eachAsync(f, iterable);
void _$consume<A>(Iterable<A> iterable, [int? n]) => consume(iterable, n);
Future<void> _$consumeAsync<A>(FxAsyncIterable<A> iterable, [int? n]) =>
    consumeAsync(iterable, n);
Future<A> _$reduceAsync<A>(
        FutureOr<A> Function(A acc, A a) f, FxAsyncIterable<A> iterable) =>
    reduceAsync(f, iterable);
Future<Acc> _$foldAsync<A, Acc>(FutureOr<Acc> seed,
        FutureOr<Acc> Function(Acc acc, A a) f, FxAsyncIterable<A> iterable) =>
    foldAsync(seed, f, iterable);
num _$sum(Iterable<num> iterable) => sum(iterable);
Future<num> _$sumAsync(FxAsyncIterable<num> iterable) => sumAsync(iterable);
double _$average(Iterable<num> iterable) => average(iterable);
Future<double> _$averageAsync(FxAsyncIterable<num> iterable) =>
    averageAsync(iterable);
num _$min(Iterable<num> iterable) => min(iterable);
Future<num> _$minAsync(FxAsyncIterable<num> iterable) => minAsync(iterable);
num _$max(Iterable<num> iterable) => max(iterable);
Future<num> _$maxAsync(FxAsyncIterable<num> iterable) => maxAsync(iterable);
int _$size<A>(Iterable<A> iterable) => size(iterable);
Future<int> _$sizeAsync<A>(FxAsyncIterable<A> iterable) => sizeAsync(iterable);
Future<String> _$joinAsync<A>(String sep, FxAsyncIterable<A> iterable) =>
    joinAsync(sep, iterable);
Map<K, List<A>> _$groupBy<A, K>(K Function(A a) f, Iterable<A> iterable) =>
    groupBy(f, iterable);
Future<Map<K, List<A>>> _$groupByAsync<A, K>(
        FutureOr<K> Function(A a) f, FxAsyncIterable<A> iterable) =>
    groupByAsync(f, iterable);
Map<K, A> _$indexBy<A, K>(K Function(A a) f, Iterable<A> iterable) =>
    indexBy(f, iterable);
Future<Map<K, A>> _$indexByAsync<A, K>(
        FutureOr<K> Function(A a) f, FxAsyncIterable<A> iterable) =>
    indexByAsync(f, iterable);
Map<K, int> _$countBy<A, K>(K Function(A a) f, Iterable<A> iterable) =>
    countBy(f, iterable);
Future<Map<K, int>> _$countByAsync<A, K>(
        FutureOr<K> Function(A a) f, FxAsyncIterable<A> iterable) =>
    countByAsync(f, iterable);
List<A> _$sort<A>(int Function(A a, A b) f, Iterable<A> iterable) =>
    sort(f, iterable);
Future<List<A>> _$sortAsync<A>(
        int Function(A a, A b) f, FxAsyncIterable<A> iterable) =>
    sortAsync(f, iterable);
List<A> _$sortBy<A>(Object? Function(A a) f, Iterable<A> iterable) =>
    sortBy(f, iterable);
Future<List<A>> _$sortByAsync<A>(
        Object? Function(A a) f, FxAsyncIterable<A> iterable) =>
    sortByAsync(f, iterable);
(List<A>, List<A>) _$partition<A>(bool Function(A a) f, Iterable<A> iterable) =>
    partition(f, iterable);
Future<(List<A>, List<A>)> _$partitionAsync<A>(
        FutureOr<bool> Function(A a) f, FxAsyncIterable<A> iterable) =>
    partitionAsync(f, iterable);

// strict/access.dart
A? _$head<A>(Iterable<A> iterable) => head(iterable);
Future<A?> _$headAsync<A>(FxAsyncIterable<A> iterable) => headAsync(iterable);
Future<A?> _$lastAsync<A>(FxAsyncIterable<A> iterable) => lastAsync(iterable);
A? _$find<A>(bool Function(A a) f, Iterable<A> iterable) => find(f, iterable);
Future<A?> _$findAsync<A>(
        FutureOr<bool> Function(A a) f, FxAsyncIterable<A> iterable) =>
    findAsync(f, iterable);
int _$findIndex<A>(bool Function(A a) f, Iterable<A> iterable) =>
    findIndex(f, iterable);
Future<int> _$findIndexAsync<A>(
        FutureOr<bool> Function(A a) f, FxAsyncIterable<A> iterable) =>
    findIndexAsync(f, iterable);
bool _$some<A>(bool Function(A a) f, Iterable<A> iterable) => some(f, iterable);
Future<bool> _$someAsync<A>(
        FutureOr<bool> Function(A a) f, FxAsyncIterable<A> iterable) =>
    someAsync(f, iterable);
Future<bool> _$everyAsync<A>(
        FutureOr<bool> Function(A a) f, FxAsyncIterable<A> iterable) =>
    everyAsync(f, iterable);
WRAPPERS

} > "$OUT"

echo "Generated $OUT"
wc -l "$OUT"

echo "Running dart analyze..."
dart analyze "$OUT"
